version: "2.4"

services:
  distil-service:
    image: distil:${PRIBERAM_DISTIL_VER}
    env_file: .env
    build:
      context: ../
      dockerfile: ./docker_cpu_py36/Dockerfile
    ports:
      - "9820:7000"
    environment:
      PYTHONUNBUFFERED: 1
      MAX_PARAGRAPHS: 40
      MAX_SENTENCE_CHARACTERS: 4096
    entrypoint: ["uvicorn", "--host", "0.0.0.0", "fastapi_web_handler:app"]
    mem_limit: 4Gb
    memswap_limit: 0Gb
    #cpus: 8.0
